import type { AnimeBlockEffect, AnimeClickEffect, AnimeEntrancePreset, AnimeHoverEffect } from '../types';

export interface AnimePresetConfig {
  name: string;
  description: string;
  duration: number;
  ease: string;
  staggerDelay: number;
  category?: 'springs' | 'cinematic' | '3d' | 'special';
}

export const ANIME_ENTRANCE_PRESETS: Record<AnimeEntrancePreset, AnimePresetConfig> = {
  // Springs & Elastic Dynamics
  springPop: {
    name: 'Anime.js Spring Pop',
    description: 'Bouncy, high-energy spring arrival that pops into viewport with elastic life.',
    duration: 750,
    ease: 'outElastic(1, .6)',
    staggerDelay: 55,
    category: 'springs',
  },
  elasticWave: {
    name: 'Anime.js Elastic Wave',
    description: 'Cascading rhythmic wave with subtle overshoot and fluid deceleration.',
    duration: 850,
    ease: 'outElastic(1, .45)',
    staggerDelay: 70,
    category: 'springs',
  },
  rubberSnap: {
    name: 'Anime.js Rubber Band Snap',
    description: 'Dynamic squash and stretch arrival with physical antiphase snap back.',
    duration: 800,
    ease: 'outElastic(1.2, .5)',
    staggerDelay: 60,
    category: 'springs',
  },
  bounceStagger: {
    name: 'Anime.js Stepped Bounce',
    description: 'Cascading double-bounce physics settling smoothly into floor position.',
    duration: 850,
    ease: 'outBounce',
    staggerDelay: 65,
    category: 'springs',
  },
  kineticDrop: {
    name: 'Anime.js Kinetic Drop',
    description: 'Gravitational bounce effect inspired by physical mechanical drops.',
    duration: 900,
    ease: 'outBounce',
    staggerDelay: 60,
    category: 'springs',
  },

  // Cinematic & Smooth Decelerations
  cinematicGlide: {
    name: 'Anime.js Cinematic Glide',
    description: 'Silky smooth exponential glide with ultra-refined deceleration curve.',
    duration: 800,
    ease: 'outExpo',
    staggerDelay: 45,
    category: 'cinematic',
  },
  backZoom: {
    name: 'Anime.js Back Flip & Zoom',
    description: 'Snappy overshoot zoom that pulls attention directly to priority links.',
    duration: 650,
    ease: 'outBack(1.8)',
    staggerDelay: 50,
    category: 'cinematic',
  },
  floatAscend: {
    name: 'Anime.js Zero-G Ascend',
    description: 'Weightless low-gravity floating arrival with smooth ease-out settle.',
    duration: 950,
    ease: 'outCubic',
    staggerDelay: 55,
    category: 'cinematic',
  },
  smoothFade: {
    name: 'Anime.js Minimalist Fade',
    description: 'Ultra-clean opacity crossfade with subtle vertical positioning.',
    duration: 600,
    ease: 'outQuad',
    staggerDelay: 40,
    category: 'cinematic',
  },
  snapScale: {
    name: 'Anime.js Snappy Geometric Pop',
    description: 'Fast, punchy geometric pop-in for modern high-energy creator portfolios.',
    duration: 550,
    ease: 'outBack(1.5)',
    staggerDelay: 35,
    category: 'cinematic',
  },

  // 3D Perspectives & Rotations
  flip3dX: {
    name: 'Anime.js 3D Horizon Flip X',
    description: 'Rotates 90° into view on horizontal 3D perspective axis with depth.',
    duration: 750,
    ease: 'outExpo',
    staggerDelay: 55,
    category: '3d',
  },
  flip3dY: {
    name: 'Anime.js 3D Card Turn Y',
    description: 'Rotates into view on vertical Y-axis like a flipping playing card.',
    duration: 750,
    ease: 'outExpo',
    staggerDelay: 55,
    category: '3d',
  },
  spiralUnfold: {
    name: 'Anime.js Vortex Spiral Unfold',
    description: 'Rotates 180° while scaling up from central focal point.',
    duration: 850,
    ease: 'outBack(1.4)',
    staggerDelay: 60,
    category: '3d',
  },
  zoomRotate: {
    name: 'Anime.js Swirling Zoom In',
    description: 'Dynamic clockwise vortex entry with rapid angular damping.',
    duration: 800,
    ease: 'outCubic',
    staggerDelay: 50,
    category: '3d',
  },
  curtainOpen: {
    name: 'Anime.js 3D Curtain Fold',
    description: 'Spatial bifold reveal unfolding outward from the center fold line.',
    duration: 800,
    ease: 'outExpo',
    staggerDelay: 60,
    category: '3d',
  },

  // Specialized FX & Optical Physics
  blurFocus: {
    name: 'Anime.js Optical Blur Resolve',
    description: 'Interpolates from deep optical camera blur (16px) to razor sharp clarity.',
    duration: 750,
    ease: 'outExpo',
    staggerDelay: 50,
    category: 'special',
  },
  slideSkew: {
    name: 'Anime.js Velocity Skew',
    description: 'Lateral arrival sheared with dynamic speed skew angle.',
    duration: 700,
    ease: 'outExpo',
    staggerDelay: 45,
    category: 'special',
  },
  cascadeStagger: {
    name: 'Anime.js Waterfall Cascade',
    description: 'Steep waterfall descent where each block settles with crisp impact.',
    duration: 750,
    ease: 'outQuart',
    staggerDelay: 80,
    category: 'special',
  },
  swingDrop: {
    name: 'Anime.js Pendulum Swing Drop',
    description: 'Suspended pendulum drop swinging across rotational arc into place.',
    duration: 900,
    ease: 'outElastic(1.1, .4)',
    staggerDelay: 70,
    category: 'special',
  },
  pulseExpand: {
    name: 'Anime.js Pulse Radial Expand',
    description: 'Originates from luminous focal pulse expanding out to block bounds.',
    duration: 750,
    ease: 'outBack(1.6)',
    staggerDelay: 55,
    category: 'special',
  },
  glitchFlicker: {
    name: 'Anime.js Cyber Glitch Pop',
    description: 'Staccato digital glitch flashes resolving into solid position.',
    duration: 650,
    ease: 'steps(5)',
    staggerDelay: 50,
    category: 'special',
  },
};

/* ==========================================================================
   ANIME.JS BLOCK ANIMATION CHOICES CATALOG
   ========================================================================== */

export interface BlockEffectMetadata {
  id: AnimeBlockEffect;
  name: string;
  category: 'attention' | 'entrance' | 'text' | 'none';
  categoryLabel: string;
  description: string;
  badge: string;
  iconName: string;
  isContinuous?: boolean;
}

export const ANIME_BLOCK_EFFECTS: BlockEffectMetadata[] = [
  // --- NONE ---
  {
    id: 'none',
    name: 'Standard (Static)',
    category: 'none',
    categoryLabel: 'Default',
    description: 'Clean, no continuous or special animation applied.',
    badge: 'Static',
    iconName: 'Minus',
  },

  // --- ATTENTION & AMBIENT LOOPS ---
  {
    id: 'pulseGlow',
    name: 'Luminous Pulse Glow',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Breathing luminous halo & soft scale oscillation using Anime.js sine curve.',
    badge: 'Sine Loop',
    iconName: 'Sparkles',
    isContinuous: true,
  },
  {
    id: 'floating',
    name: 'Weightless Levitate',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Cosmic zero-gravity hover translating vertically on continuous sine wave.',
    badge: 'Float FX',
    iconName: 'Cloud',
    isContinuous: true,
  },
  {
    id: 'heartbeat',
    name: 'Cardiac Heartbeat',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Dual rhythmic cardiac thump that commands immediate viewer focus.',
    badge: 'Keyframe Loop',
    iconName: 'Heart',
    isContinuous: true,
  },
  {
    id: 'rubberBand',
    name: 'Elastic Rubber Band',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Squash & stretch elasticity driven by physical antiphase scale transforms.',
    badge: 'Physics Loop',
    iconName: 'Activity',
    isContinuous: true,
  },
  {
    id: 'gentleWobble',
    name: 'Pendulum Wobble',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Subtle rhythmic tilt rocking like an acoustic pendulum with damped settle.',
    badge: 'Rotational',
    iconName: 'Compass',
    isContinuous: true,
  },
  {
    id: 'jiggleAlert',
    name: 'Urgent Jiggle Alert',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'High-frequency elastic shake designed for callouts and priority badges.',
    badge: 'Alert FX',
    iconName: 'Bell',
    isContinuous: true,
  },
  {
    id: 'springBounce',
    name: 'Playful Spring Bounce',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Gravitational hop with kinetic contact squash and elastic rebound.',
    badge: 'Bounce Loop',
    iconName: 'Zap',
    isContinuous: true,
  },
  {
    id: 'shimmerGleam',
    name: 'Prismatic Shimmer',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Light reflection sweep travelling across block surface.',
    badge: 'Gleam FX',
    iconName: 'Sun',
    isContinuous: true,
  },
  {
    id: 'rainbowBorder',
    name: 'Chromatic Border Glow',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Continuously interpolates vibrant color spectrum along card border.',
    badge: 'Color Tween',
    iconName: 'Palette',
    isContinuous: true,
  },
  {
    id: 'neonFlicker',
    name: 'Cyber Neon Flicker',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Intermittent gas filament flicker with stepped luminescence micro-dips.',
    badge: 'Retro Neon',
    iconName: 'Flame',
    isContinuous: true,
  },
  {
    id: 'breathScale',
    name: 'Zen Meditative Breath',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Slow, expansive breathing motion that gives blocks subtle organic life.',
    badge: 'Soft Breath',
    iconName: 'Wind',
    isContinuous: true,
  },
  {
    id: 'glitchShift',
    name: 'Cyber Matrix Glitch',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Subtle high-frequency horizontal matrix jitter with color aberration.',
    badge: 'Glitch Loop',
    iconName: 'Activity',
    isContinuous: true,
  },
  {
    id: 'radarPing',
    name: 'Sonar Radar Ping',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Periodic radiating aura ring propagating outward like radar sonar.',
    badge: 'Radar Wave',
    iconName: 'Waves',
    isContinuous: true,
  },
  {
    id: 'colorCycle',
    name: 'Chromatic Spectrum Shift',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Continuous linear hue rotation across border and glow shadows.',
    badge: 'Color Tween',
    iconName: 'Palette',
    isContinuous: true,
  },
  {
    id: 'orbitGlow',
    name: 'Traveling Orbital Glow',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Dynamic localized spotlight circulating continuously around perimeter.',
    badge: 'Orbit FX',
    iconName: 'Sun',
    isContinuous: true,
  },
  {
    id: 'pendulumSwing',
    name: 'Harmonic Pendulum Swing',
    category: 'attention',
    categoryLabel: 'Ambient Loop',
    description: 'Physically calculated rhythmic pendulum swing with angular velocity damping.',
    badge: 'Harmonic',
    iconName: 'Compass',
    isContinuous: true,
  },

  // --- ENTRANCE FX ---
  {
    id: 'springPop',
    name: 'Elastic Spring Pop',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'High-energy spring physics arrival with elastic overshoot (outElastic).',
    badge: 'Spring Engine',
    iconName: 'Sparkle',
  },
  {
    id: 'elasticWave',
    name: 'Liquid Elastic Wave',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Cascading liquid ripple entrance with fluid spring overshoot.',
    badge: 'Wave Curve',
    iconName: 'Waves',
  },
  {
    id: 'backZoom',
    name: 'Snappy Back Zoom',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Snappy zoom from depth with outBack(1.8) deceleration overshoot.',
    badge: 'Back Overshoot',
    iconName: 'Maximize2',
  },
  {
    id: 'kineticDrop',
    name: 'Gravitational Kinetic Drop',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Realistic gravity drop from above with natural ground bounces.',
    badge: 'outBounce',
    iconName: 'ArrowDown',
  },
  {
    id: 'cinematicGlide',
    name: 'Cinematic Expo Glide',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Silky smooth exponential deceleration glide (outExpo) from bottom.',
    badge: 'Expo Glide',
    iconName: 'Film',
  },
  {
    id: 'flip3dX',
    name: '3D Horizon Flip (X-Axis)',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Rotates 90° into view on horizontal 3D perspective axis.',
    badge: 'Perspective 3D',
    iconName: 'Layers',
  },
  {
    id: 'flip3dY',
    name: '3D Card Turn (Y-Axis)',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Rotates into view on vertical Y-axis like a flipping playing card.',
    badge: 'Perspective 3D',
    iconName: 'RefreshCw',
  },
  {
    id: 'spiralUnfold',
    name: 'Vortex Spiral Unfold',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Rotates 180° while scaling up from central focal point.',
    badge: 'Rotational 3D',
    iconName: 'Disc',
  },
  {
    id: 'blurFocus',
    name: 'Optical Blur Resolve',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Interpolates from deep optical camera blur (14px) to razor sharp clarity.',
    badge: 'Filter Blur',
    iconName: 'Eye',
  },
  {
    id: 'slideSkew',
    name: 'Kinetic Velocity Skew',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Lateral arrival sheared with dynamic speed skew angle.',
    badge: 'Skew Transform',
    iconName: 'FastForward',
  },
  {
    id: 'zoomRotate',
    name: 'Swirling Vortex Zoom',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Dynamic clockwise swirling entry with rapid angular damping.',
    badge: 'Vortex In',
    iconName: 'Disc',
  },
  {
    id: 'cascadeStagger',
    name: 'Waterfall Cascade',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Cascading steep descent settling with crisp impact deceleration.',
    badge: 'Waterfall',
    iconName: 'ArrowDown',
  },
  {
    id: 'swingDrop',
    name: 'Suspended Pendulum Drop',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Suspended drop swinging through rotational arc into final equilibrium.',
    badge: 'Arc Swing',
    iconName: 'Compass',
  },
  {
    id: 'rubberSnap',
    name: 'Rubber Band Snap In',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Dynamic squash and stretch arrival with physical antiphase snap back.',
    badge: 'Elastic Snap',
    iconName: 'Activity',
  },
  {
    id: 'pulseExpand',
    name: 'Radial Pulse Reveal',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Originates from luminous focal pulse expanding out to block bounds.',
    badge: 'Pulse Reveal',
    iconName: 'Sparkles',
  },
  {
    id: 'curtainOpen',
    name: '3D Spatial Curtain Fold',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Spatial bifold reveal unfolding outward from central axis.',
    badge: 'Bifold 3D',
    iconName: 'Layers',
  },
  {
    id: 'glitchFlicker',
    name: 'Cyber Glitch Pop In',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Staccato digital glitch flashes resolving into solid position.',
    badge: 'Cyber Glitch',
    iconName: 'Zap',
  },
  {
    id: 'floatAscend',
    name: 'Zero-G Smooth Ascend',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Weightless low-gravity floating arrival with smooth ease-out settle.',
    badge: 'Zero-G',
    iconName: 'Cloud',
  },
  {
    id: 'snapScale',
    name: 'Snappy Geometric Pop',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Fast, punchy geometric pop-in for modern high-energy creator portfolios.',
    badge: 'Punchy Pop',
    iconName: 'Maximize2',
  },
  {
    id: 'smoothFade',
    name: 'Minimalist Soft Fade',
    category: 'entrance',
    categoryLabel: 'Entrance Reveal',
    description: 'Ultra-clean opacity crossfade with subtle vertical positioning.',
    badge: 'Pure Fade',
    iconName: 'Minus',
  },

  // --- TEXT & TYPOGRAPHY FX ---
  {
    id: 'scrambleDecode',
    name: 'Cyber Hacker Scramble',
    category: 'text',
    categoryLabel: 'Typography FX',
    description: 'Real Anime.js text cipher algorithm scrambling glyphs into settled characters.',
    badge: 'Scramble Engine',
    iconName: 'Terminal',
  },
  {
    id: 'typewriterStagger',
    name: 'Staggered Character Cascade',
    category: 'text',
    categoryLabel: 'Typography FX',
    description: 'Anime.js stagger() reveal across letters with typewriter precision.',
    badge: 'Stagger Text',
    iconName: 'Type',
  },
  {
    id: 'waveLetters',
    name: 'Undulating Letter Wave',
    category: 'text',
    categoryLabel: 'Typography FX',
    description: 'Letter-by-letter rhythmic sine bounce wave propagating across headline.',
    badge: 'Wave Text',
    iconName: 'Sliders',
  },
  {
    id: 'blurToClearText',
    name: 'Optical Blur Word Focus',
    category: 'text',
    categoryLabel: 'Typography FX',
    description: 'Per-word cinematic depth blur interpolating into sharp typography.',
    badge: 'Blur Words',
    iconName: 'Eye',
  },
  {
    id: 'fadeSlideWords',
    name: 'Cascading Words Slide Up',
    category: 'text',
    categoryLabel: 'Typography FX',
    description: 'Word-by-word staggered upward slide with smooth exponential deceleration.',
    badge: 'Word Stagger',
    iconName: 'FastForward',
  },
  {
    id: 'neonTextFlicker',
    name: 'Neon Sign Letter Glow',
    category: 'text',
    categoryLabel: 'Typography FX',
    description: 'Individual neon character glow surge with warm luminous shadows.',
    badge: 'Neon Glow',
    iconName: 'Flame',
  },
];

export const ANIME_HOVER_OPTIONS: { id: AnimeHoverEffect; name: string; description: string }[] = [
  { id: 'none', name: 'Default', description: 'Standard subtle highlight' },
  { id: 'magneticLift', name: 'Magnetic Lift & Elastic', description: '-4px vertical elevation with spring overshoot' },
  { id: 'tilt3d', name: 'Interactive 3D Tilt', description: 'Dynamic 3D perspective tilt tracking' },
  { id: 'glowSurge', name: 'Luminance Glow Surge', description: 'Box-shadow intensity surge driven by Anime.js' },
  { id: 'springPress', name: 'Tactile Squash Press', description: 'Slight mechanical squash on hover with snappy return' },
  { id: 'rotatePlayful', name: 'Playful Tilt Angle', description: 'Subtle 3-degree angular tilt with damped bounce' },
  { id: 'harmonicPulse', name: 'Harmonic Scale Breathing', description: 'Continuous gentle breathing oscillation while hovered' },
  { id: 'glitchMicro', name: 'Cyber Micro-Jitter', description: 'Rapid digital micro-displacement on pointer hover' },
  { id: 'scalePop', name: 'Snappy Scale Pop (1.05x)', description: 'Fast geometric scale surge with crisp ease' },
  { id: 'skewFloat', name: 'Velocity Skew Float', description: 'Dynamic horizontal skew velocity with float lift' },
];

export const ANIME_CLICK_OPTIONS: { id: AnimeClickEffect; name: string; description: string }[] = [
  { id: 'none', name: 'Default', description: 'Standard link transition' },
  { id: 'rippleWave', name: 'Liquid Ripple Wave', description: 'Expanding radial wave originating from touch coords' },
  { id: 'confettiBurst', name: 'Confetti Particle Burst', description: 'Physics particles bursting in all directions' },
  { id: 'shockwave', name: 'Sonic Shockwave Ring', description: 'Expanding glowing ring radiating outward' },
  { id: 'squashPop', name: 'Physical Squash & Pop', description: 'Compression squash with elastic rebound' },
  { id: 'flashBurst', name: 'Luminous Flash Burst', description: 'Instant white light flash flood expanding outward' },
  { id: 'elasticBounce', name: 'Deep Elastic Compression', description: 'Deep mechanical compression with high-amplitude bounce' },
  { id: 'stampPress', name: 'Tactile 3D Stamp Press', description: 'Crisp sunken 3D stamp press down with tactile click' },
  { id: 'particleSparks', name: 'Electric Spark Sparks', description: 'Scattered high-velocity kinetic spark particles' },
  { id: 'hapticVibrate', name: 'Simulated Haptic Pulse', description: 'Rapid double micro-buzz haptic simulation' },
];
