import React, { useCallback, useEffect, useState } from 'react';
import { CalendarCheck, Check, Clock3, Loader2, X } from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { BookingRequest, loadBookingRequests, updateBookingRequest } from '../../services/bookingService';

export const BookingsPanel: React.FC = () => {
  const { activeProfile, showToast } = useApp();
  const [bookings, setBookings] = useState<BookingRequest[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setBookings(await loadBookingRequests(activeProfile.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load booking requests.'); } finally { setLoading(false); } }, [activeProfile.id]);
  useEffect(() => { void refresh(); }, [refresh]);
  const update = async (booking: BookingRequest, status: 'confirmed' | 'declined') => { setBusyId(booking.id); setError(null); try { await updateBookingRequest(booking.id, status); showToast?.(status === 'confirmed' ? 'Booking confirmed and requester notified.' : 'Booking request declined.'); await refresh(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to update booking request.'); } finally { setBusyId(null); } };
  return <div className="space-y-5"><div className="rounded-2xl border border-line bg-surface p-5"><div className="flex items-center gap-2 text-sm font-bold text-ink"><CalendarCheck className="h-4 w-4 text-accent" />Booking requests</div><p className="mt-1 text-xs leading-5 text-muted">Review preferred times and confirm availability. Confirmed requesters receive an email when delivery is configured.</p></div>{error && <div role="alert" className="rounded-xl border border-danger/30 bg-danger/5 px-4 py-3 text-xs text-danger">{error}</div>}<div className="rounded-2xl border border-line bg-surface">{loading ? <div className="p-10 text-center text-xs text-muted"><Loader2 className="mx-auto mb-2 h-5 w-5 animate-spin" />Loading requests…</div> : bookings.length === 0 ? <div className="p-10 text-center"><CalendarCheck className="mx-auto h-8 w-8 text-subtle" /><p className="mt-2 text-sm font-semibold text-body">No booking requests yet</p><p className="mt-1 text-xs text-muted">New requests will appear here after visitors choose a date and time.</p></div> : <div className="divide-y divide-line">{bookings.map((booking) => <div key={booking.id} className="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><div className="text-sm font-semibold text-ink">{booking.requester_name || booking.requester_email}</div><div className="mt-1 flex flex-wrap items-center gap-2 text-xs text-muted"><Clock3 className="h-3.5 w-3.5" />{new Date(booking.requested_start).toLocaleString()} · {booking.duration_minutes} minutes · {booking.requester_email}</div><div className="mt-1 text-xs text-muted">Status: <span className="font-semibold capitalize text-body">{booking.status}</span></div></div>{booking.status === 'pending' && <div className="flex items-center gap-2 self-start sm:self-auto"><button type="button" onClick={() => void update(booking, 'declined')} disabled={busyId === booking.id} className="inline-flex items-center gap-1.5 rounded-xl border border-line px-3 py-1.5 text-xs font-semibold text-body hover:border-danger/30 hover:text-danger disabled:opacity-50"><X className="h-3.5 w-3.5" />Decline</button><button type="button" onClick={() => void update(booking, 'confirmed')} disabled={busyId === booking.id} className="inline-flex items-center gap-1.5 rounded-xl bg-accent px-3 py-1.5 text-xs font-bold text-white hover:opacity-90 disabled:opacity-50"><Check className="h-3.5 w-3.5" />Confirm</button></div>}</div>)}</div>}</div></div>;
};
